const BlogData = [
  {
    id: 1,
    date: "November 5, 2024",
    category: "Charity",
    title: "Feed a child project",
    cover: "/images/fachild.jpeg",
    para: "Providing hot meals for the children in rural communities",
    desc: "This program is aimed to help school children have balanced diets as they learn in school in rural communities.",
  },
    {
        id: 1,
        date: "January 21, 2021",
        category: "Health",
        title: "Teen Pregnancy Awareness",
        cover: "/images/singlepage/teen-pregnancy.jpeg",
        para: "The Teen Pregnancy Awareness initiative, held on January 21, 2021, aimed to address the pressing issue of teen pregnancy and raise awareness within the community.",
        desc: "The Teen Pregnancy Awareness initiative, held on January 21, 2021, aimed to address the pressing issue of teen pregnancy and raise awareness within the community. This event shed light on the challenges faced by teenagers dealing with pregnancy and emphasized the importance of education and support systems. It provided a platform for open discussions and offered resources to help teenagers make informed decisions about their reproductive health. By fostering understanding and empathy, the initiative sought to contribute to the well-being and future prospects of young individuals in our community.",
      },
      
   
      
    {
      id: 2,
      date: "January 15, 2021",
      catgeory: "Healthy-living",
      title: "Free Medical Checkup",
      cover: "/images/singlepage/blog-2.jpeg",
      para: "The Free Medical Checkup event, held on January 15, 2021, was a significant initiative in the field of traveling and healthcare. ",
      desc: "The Free Medical Checkup event, held on January 15, 2021, was a significant initiative in the field of traveling and healthcare. It provided an opportunity for travelers and local communities to access free medical services, ensuring their well-being during their journeys. This event exemplified the importance of community support and the impact of offering medical assistance to those in need. It was a remarkable day, where the spirit of traveling and healthcare converged to make a positive difference in people's lives.",
    },
    {
      id: 3,
      date: "March 16, 2023",
      catgeory: "Legal",
      title: "Legal Representation against Abuse",
      cover: "/images/singlepage/blog-3.jpeg",
      para: "“Abuse” in this context means physical or mental abuse, including sexual abuse, and abuse in the form of violence, neglect, maltreatment and exploitation.",
      desc: "You may be entitled to legal aid for a private family law dispute (Child Arrangements Order, Prohibited Steps Order, or Specific Issue Order) if your child is at risk of abuse and you can’t afford to pay legal costs. Anyone with the care of a child may seek to protect them; for example, a grandmother with the care of a child may seek to prevent the child’s father from having contact.On January 8th 2018, changes to the eligibility requirements for legal aid in family law private disputes came into effect. There is no longer a time limit on abuse evidence, which previously stood at five years. Additionally, the range of documents accepted as evidence of abuse has been widened to include statements from domestic violence support organisations and housing support officers.",
    },
    {
      id: 4,
      date: "November 30, 2022",
      catgeory: "Health",
      title: "Immunization and its benefits",
      cover: "/images/singlepage/immunization.jpeg",
      para: "Immunization is a global health and development success story, saving millions of lives every year. Vaccines reduce risks of getting a disease by working with your body’s natural defences to build protection.",
      desc: "Immunization is a global health and development success story, saving millions of lives every year. Vaccines reduce risks of getting a disease by working with your body’s natural defences to build protection. When you get a vaccine, your immune system responds.We now have vaccines to prevent more than 20 life-threatening diseases, helping people of all ages live longer, healthier lives. Immunization currently prevents 3.5-5 million deaths every year from diseases like diphtheria, tetanus, pertussis, influenza and measles.Immunization is a key component of primary health care and an indisputable human right. It’s also one of the best health investments money can buy. Vaccines are also critical to the prevention and control of infectious disease outbreaks. They underpin global health security and will be a vital tool in the battle against antimicrobial resistance.",
    },
    {
      id: 5,
      date: "January 10, 2022",
      catgeory: "Content Writing",
      title: "Education",
      cover: "/images/singlepage/blog-5.jpeg",
      para: "The 'Education' initiative, which took place on January 10, 2022, focused on the importance of quality education and its role in shaping the future.",
      desc: "The 'Education' initiative, which took place on January 10, 2022, focused on the importance of quality education and its role in shaping the future. This event, hosted under the category of 'Content Writing,' brought together content creators, educators, and enthusiasts to discuss and promote educational content that makes a meaningful impact. The event emphasized the power of knowledge, learning, and effective communication in today's information-driven world. Attendees explored various aspects of content creation related to education, such as e-learning, instructional design, and educational content marketing. 'Education' aimed to inspire content creators to contribute to the dissemination of knowledge and the improvement of educational resources available to learners worldwide.",
    },
    {
      id: 6,
      date: "January 18, 2021",
      catgeory: "Nutrition",
      title: "Mal-Nutrition in Pregnancy",
      cover: "/images/singlepage/nitient.jpeg",
      para: "Most women in Nigeria do not meet the recommendations for healthful nutrition and weight before and during pregnancy. Women and providers often ask what a healthy diet for a pregnant woman should look like.",
      desc: "Most women in Nigeria do not meet the recommendations for healthful nutrition and weight before and during pregnancy. Women and providers often ask what a healthy diet for a pregnant woman should look like. The message should be “eat better, not more.” This can be achieved by basing diet on a variety of nutrient-dense, whole foods, including fruits, vegetables, legumes, whole grains, healthy fats with omega-3 fatty acids that include nuts and seeds, and fish, in place of poorer quality highly processed foods. Such a diet embodies nutritional density and is less likely to be accompanied by excessive energy intake than the standard American diet consisting of increased intakes of processed foods, fatty red meat, and sweetened foods and beverages. Women who report “prudent” or “health-conscious” eating patterns before and/or during pregnancy may have fewer pregnancy complications and adverse child health outcomes."
    },
    {
      id: 6,
      date: "January 12, 2014",
      catgeory: "Business Strategy",
      title: "Drug Abuse Remedy",
      cover: "/images/singlepage/drugabuse.webp",
      para: "The initiative to hold an event that talked about the dangers of drug abuse ad educate the youth on how easy it was to get addicted to drug use which can in turn cause untold hamr and damage to their systems and their lives",
      desc: "The initiative to hold an event that talked about the dangers of drug abuse ad educate the youth on how easy it was to get addicted to drug use which can in turn cause untold hamr and damage to their systems and their lives. The program also included mentorship and counselling for youths already using drugs to stop them from further use and introduce them to a community that will help foster their staying off drugs",
    },
    {
      id: 7,
      date: "January 30, 2019",
      catgeory: "Business",
      title: "Business Loans",
      cover: "/images/singlepage/blog-71.jpeg",
      para: "A program was held by the solomons haven foundation for poor and struggling women who are engaged in mini trading, the aim of",
      desc: "A program was held by the solomons haven foundation for poor and struggling women who are engaged in mini trading, the aim of the program was to create an avenue for financial stipends and aids needed for business growth to be given to the women who needs it, to help promote their business and help generate income for the households of the women. This is a generous and great development that was applauded by the beneficiaries.",
    },
    {
      id: 8,
      date: "January 10, 2022",
      catgeory: "Content Writing",
      title: "Book Club",
      cover: "/images/singlepage/book-club.png",
      para: "The Solomons Haven Book Club is a social club establised to encourage young people to engage in reading and give them a community of friends with like minds",
      desc: "The Solomons Haven Book Club is a social club establised to encourage young people to engage in reading and give them a community of friends with like minds who love to read and like to see the world through the pages of a book. it is a really cool initiative and i would encourage all young people who love reading to join.",
    },
    {
      id: 9,
      date: "January 10, 2025",
      catgeory: "Charity",
      title: "Annual Meet Their Need, 2024",
      cover: "/images/singlepage/meetneed.jpeg",
      para: "Annual Meet Their Needs Program 2024",
      desc: "The Annual Meet Their Needs Program 2024 aimed to give back to society by supporting the less privileged. This initiative provided essential resources—food, clothing, medical care, and educational supplies—to underserved communities. Proudly sponsored by the Josephus Foundation, the program was able to reach more individuals and expand its impact. The foundation’s support allowed us to mobilize volunteers, secure necessary resources, and ensure the program's success. Throughout the event, attendees received not only physical essentials but also emotional support. Volunteers interacted with children, offering fun activities and mentorship, while adults had access to medical consultations and workshops on mental health and personal development. The program served hundreds of families, providing hope and a sense of community to those in need. The 2024 edition set the stage for future growth, with plans for more comprehensive support in the coming years. We are deeply grateful to the Josephus Foundation for their generous sponsorship, and we look forward to expanding the program to continue making a meaningful difference in the lives of those who need it most.",
      additionalImages: [
        "/images/meet1.jpeg",
        "/images/meet2.jpeg",
        "/images/meet3.jpeg",
        "/images/meet4.jpeg",
        "/images/meet5.jpeg",
        "/images/meet6.jpeg",
        "/images/meet7.jpeg",
        "/images/meet8.jpeg",
        "/images/meet9.jpeg",
        "/images/meet10.jpeg"
      ]
    },
  ]
  
  export default BlogData